apiVersion: v1
kind: Pod
metadata:
  name: simple-api-server
  labels:
    app: simple-api-server-pod
spec:
  containers:
    - name: simple-api-server
      image: choonsiong/simple-api-server
      ports:
        - containerPort: 8080