apiVersion: v1
kind: Service
metadata:
  name: simple-api-server-service
spec:
    selector:
        type: frontend
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
