apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip-service
spec:
  type: ClusterIP # it is default if we didn't specify
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: my-web-app
    type: backend