apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: my-web-app
    type: backend