apiVersion: v2
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  type: NodePort
  ports: # array of ports
    - targetPort: 80
      port: 80
      nodePort: 30001
  selector:
    app: my-web-app
    type: frontend